[tool.ruff]
# Allow unused variables when underscore-prefixed.
target-version = "py38"
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
builtins = ["_"]
line-length = 120
exclude = [
    "tests",
]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "R",  # Refactor
]
ignore = [
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "B905",  # zip() strict parameter checking
    "RET503", # missing explicit return
    "RET504", # unnecessary assignment
    "RET505", # unnecessary else/elif after return statement
    "W191",  # indentation contains tabs(ruff will fix it)
    "E501",  # line too long(ruff will fix it)
]
# Allow autofix for all enabled rules (when `--fix`) is provided.
unfixable = []

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.isort]
known-third-party = []

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

